#!/bin/sh

stack_name=$1

[ "$stack_name" ] || exit 1

heat-output $stack_name > _outputs.yml || exit 1
filler -p _outputs.yml templates/hosts > hosts
filler -p _outputs.yml templates/ssh_config > ssh_config

