#!/bin/sh

curl -o /usr/local/bin/crux https://raw2.github.com/larsks/crux/master/crux
chmod 755 /usr/local/bin/crux

# Because this is so much easier than multiple keystone
# invocations.
/usr/local/bin/crux --user demo:demo::demo

if ! glance image-show cirros > /dev/null 2>&1; then
glance image-create \
	--copy-from http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img \
	--is-public true \
	--container-format bare \
	--disk-format raw \
	--name cirros
fi

neutron net-create external --router:external=True
neutron subnet-create --disable-dhcp external 172.16.13.0/24

nova flavor-create m1.nano auto 128 1 1

export OS_TENANT_ID=
export OS_TENANT_NAME=demo
export OS_USERNAME=demo
export OS_PASSWORD=demo

neutron router-create extrouter
neutron router-gateway-set extrouter external
neutron net-create net0
neutron subnet-create --name net0-subnet0 net0 10.0.0.0/24
neutron router-interface-add extrouter net0-subnet0


